// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Board struct {
	ID     string   `json:"id"`
	Title  string   `json:"title"`
	Shapes []*Shape `json:"shapes"`
}

type Mutation struct {
}

type Query struct {
}

type Shape struct {
	ID          string    `json:"id"`
	BoardID     string    `json:"boardId"`
	Type        ShapeType `json:"type"`
	X           float64   `json:"x"`
	Y           float64   `json:"y"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Text        *string   `json:"text,omitempty"`
	Rotation    float64   `json:"rotation"`
	ZIndex      int       `json:"zIndex"`
	Locked      bool      `json:"locked"`
	Fill        *string   `json:"fill,omitempty"`
	Stroke      *string   `json:"stroke,omitempty"`
	StrokeWidth *float64  `json:"strokeWidth,omitempty"`
}

type ShapeInput struct {
	ID          string     `json:"id"`
	Type        *ShapeType `json:"type,omitempty"`
	X           *float64   `json:"x,omitempty"`
	Y           *float64   `json:"y,omitempty"`
	Width       *float64   `json:"width,omitempty"`
	Height      *float64   `json:"height,omitempty"`
	Text        *string    `json:"text,omitempty"`
	Rotation    *float64   `json:"rotation,omitempty"`
	ZIndex      *int       `json:"zIndex,omitempty"`
	Locked      *bool      `json:"locked,omitempty"`
	Fill        *string    `json:"fill,omitempty"`
	Stroke      *string    `json:"stroke,omitempty"`
	StrokeWidth *float64   `json:"strokeWidth,omitempty"`
}

type Subscription struct {
}

type TransientShape struct {
	ID string  `json:"id"`
	X  float64 `json:"x"`
	Y  float64 `json:"y"`
}

type TransientShapeInput struct {
	ID string  `json:"id"`
	X  float64 `json:"x"`
	Y  float64 `json:"y"`
}

type ShapeType string

const (
	ShapeTypeRect    ShapeType = "RECT"
	ShapeTypeEllipse ShapeType = "ELLIPSE"
	ShapeTypeText    ShapeType = "TEXT"
)

var AllShapeType = []ShapeType{
	ShapeTypeRect,
	ShapeTypeEllipse,
	ShapeTypeText,
}

func (e ShapeType) IsValid() bool {
	switch e {
	case ShapeTypeRect, ShapeTypeEllipse, ShapeTypeText:
		return true
	}
	return false
}

func (e ShapeType) String() string {
	return string(e)
}

func (e *ShapeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShapeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShapeType", str)
	}
	return nil
}

func (e ShapeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShapeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShapeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
