package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"

	"server/auth"
	"server/graph"
	"server/users"
)

var errBadCredentials = errors.New("invalid email or password")

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, email string, password string) (*graph.AuthPayload, error) {
	u, err := users.Register(email, password)
	if err != nil {
		if errors.Is(err, users.ErrAlreadyExists) {
			return nil, errors.New("email already registered")
		}
		return nil, err
	}
	return authPayload(u)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*graph.AuthPayload, error) {
	u, err := users.GetByEmail(email, password)
	if err != nil {
		return nil, errBadCredentials
	}
	return authPayload(u)
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken string) (*graph.AuthPayload, error) {
	claims, err := auth.ParseToken(refreshToken)
	if err != nil {
		return nil, err
	}
	u, err := users.GetByID(claims.UserID)
	if err != nil {
		return nil, err
	}
	return authPayload(u)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graph.User, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}
	u, err := users.GetByID(userID)
	if err != nil {
		return nil, nil
	}
	return &graph.User{ID: u.ID, Email: u.Email}, nil
}

func authPayload(u *users.User) (*graph.AuthPayload, error) {
	access, err := auth.GenerateAccessToken(u.ID)
	if err != nil {
		return nil, err
	}
	refresh, err := auth.GenerateRefreshToken(u.ID)
	if err != nil {
		return nil, err
	}
	return &graph.AuthPayload{
		AccessToken:  access,
		RefreshToken: refresh,
		User:         &graph.User{ID: u.ID, Email: u.Email},
	}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
