package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"server/graph"
	"server/locks"
	"server/subscriptions"
	"server/transient"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, title *string) (*graph.Board, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	return r.Boards.Create(ctx, userID, t)
}

// UpdateShape is the resolver for the updateShape field.
func (r *mutationResolver) UpdateShape(ctx context.Context, boardID string, shape graph.ShapeInput, clientID string) (*graph.Shape, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return nil, err
	}

	stored, created, err := r.Boards.UpsertShape(ctx, boardID, shape)
	if err != nil {
		return nil, err
	}

	eventType := graph.ShapeEventTypeUpdated
	if created {
		eventType = graph.ShapeEventTypeCreated
	}

	subscriptions.Publish(boardID, &graph.ShapeEvent{
		Type:     eventType,
		Shape:    stored,
		ClientID: clientID,
	})

	return stored, nil
}

// MoveShapeTransient is the resolver for the moveShapeTransient field.
func (r *mutationResolver) MoveShapeTransient(ctx context.Context, boardID string, shape graph.TransientShapeInput, clientID string) (bool, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return false, err
	}

	ts := &graph.TransientShape{
		ID:       shape.ID,
		X:        shape.X,
		Y:        shape.Y,
		Width:    shape.Width,
		Height:   shape.Height,
		ClientID: clientID,
	}

	// Публикуем в transient-пабсаб
	transient.Publish(boardID, ts)

	return true, nil
}

// MoveShapesTransient is the resolver for the moveShapesTransient field.
func (r *mutationResolver) MoveShapesTransient(ctx context.Context, boardID string, shapes []*graph.TransientShapeInput, clientID string) (bool, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return false, err
	}

	batch := &graph.TransientShapesBatch{
		ClientID: clientID,
		Shapes:   make([]*graph.TransientShape, 0, len(shapes)),
	}

	for _, s := range shapes {
		batch.Shapes = append(batch.Shapes, &graph.TransientShape{
			ID:       s.ID,
			X:        s.X,
			Y:        s.Y,
			Width:    s.Width,
			Height:   s.Height,
			ClientID: clientID,
		})
	}

	transient.PublishBatch(boardID, batch)

	return true, nil
}

// DeleteShape is the resolver for the deleteShape field.
func (r *mutationResolver) DeleteShape(ctx context.Context, boardID string, shapeID string) (bool, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return false, err
	}

	deleted, err := r.Boards.DeleteShape(ctx, boardID, shapeID)
	if err != nil {
		return false, err
	}

	if deleted != nil {
		subscriptions.Publish(boardID, &graph.ShapeEvent{
			Type:     graph.ShapeEventTypeDeleted,
			Shape:    deleted,
			ClientID: "system",
		})
	}

	return deleted != nil, nil
}

// SetShapeLock is the resolver for the setShapeLock field.
func (r *mutationResolver) SetShapeLock(ctx context.Context, boardID string, shapeID string, clientID string, action graph.LockAction) (bool, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return false, err
	}

	locks.Publish(boardID, &graph.LockEvent{
		ShapeID:  shapeID,
		ClientID: clientID,
		Action:   action,
	})

	return true, nil
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*graph.Board, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.Boards.Get(ctx, id, userID)
}

// MyBoards is the resolver for the myBoards field.
func (r *queryResolver) MyBoards(ctx context.Context) ([]*graph.Board, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.Boards.ListForUser(ctx, userID)
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello, world!", nil
}

// ShapeMoved is the resolver for the shapeMoved field.
func (r *subscriptionResolver) ShapeMoved(ctx context.Context, boardID string) (<-chan *graph.TransientShape, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return nil, err
	}

	ch := make(chan *graph.TransientShape, 1)
	transient.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		transient.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// ShapesMoved is the resolver for the shapesMoved field.
func (r *subscriptionResolver) ShapesMoved(ctx context.Context, boardID string) (<-chan *graph.TransientShapesBatch, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return nil, err
	}

	ch := make(chan *graph.TransientShapesBatch, 1)
	transient.SubscribeBatch(boardID, ch)

	go func() {
		<-ctx.Done()
		transient.UnsubscribeBatch(boardID, ch)
	}()

	return ch, nil
}

// ShapeEvents is the resolver for the shapeEvents field.
func (r *subscriptionResolver) ShapeEvents(ctx context.Context, boardID string) (<-chan *graph.ShapeEvent, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return nil, err
	}

	ch := make(chan *graph.ShapeEvent, 1)
	subscriptions.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		subscriptions.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// ShapeLocks is the resolver for the shapeLocks field.
func (r *subscriptionResolver) ShapeLocks(ctx context.Context, boardID string) (<-chan *graph.LockEvent, error) {
	if _, err := r.requireBoardAccess(ctx, boardID); err != nil {
		return nil, err
	}

	ch := make(chan *graph.LockEvent, 1)
	locks.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		locks.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
