package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"server/graph"
	"server/storage"
	"server/subscriptions"
	"server/transient"
)

// UpdateShape is the resolver for the updateShape field.
func (r *mutationResolver) UpdateShape(ctx context.Context, boardID string, shape graph.ShapeInput, clientID string) (*graph.Shape, error) {
	storage.BoardsMu.Lock()
	defer storage.BoardsMu.Unlock()

	board, exists := storage.Boards[boardID]
	if !exists {
		board = &graph.Board{
			ID:     boardID,
			Title:  "New Board",
			Shapes: []*graph.Shape{},
		}
		storage.Boards[boardID] = board
	}

	var existing *graph.Shape
	for _, s := range board.Shapes {
		if s.ID == shape.ID {
			existing = s
			break
		}
	}

	if existing == nil {
		existing = &graph.Shape{
			ID:       shape.ID,
			BoardID:  boardID,
			Rotation: 0,
			ZIndex:   0,
			Locked:   false,
		}
		board.Shapes = append(board.Shapes, existing)
	}

	// применяем PATCH
	storage.ApplyShapePatch(existing, shape)

	// шлём persisted-ивент
	subscriptions.Publish(boardID, existing)

	return existing, nil
}

// MoveShapeTransient is the resolver for the moveShapeTransient field.
func (r *mutationResolver) MoveShapeTransient(ctx context.Context, boardID string, shape graph.TransientShapeInput, clientID string) (bool, error) {
	ts := &graph.TransientShape{
		ID:     shape.ID,
		X:      shape.X,
		Y:      shape.Y,
		Width:  shape.Width,
		Height: shape.Height,
	}

	// Публикуем в transient-пабсаб
	transient.Publish(boardID, ts)

	return true, nil
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*graph.Board, error) {
	storage.BoardsMu.RLock()
	defer storage.BoardsMu.RUnlock()

	if board, ok := storage.Boards[id]; ok {
		return board, nil
	}

	board := &graph.Board{
		ID:     id,
		Title:  "New Board",
		Shapes: []*graph.Shape{},
	}
	storage.Boards[id] = board
	return board, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello, world!", nil
}

// ShapeMoved is the resolver for the shapeMoved field.
func (r *subscriptionResolver) ShapeMoved(ctx context.Context, boardID string) (<-chan *graph.TransientShape, error) {
	ch := make(chan *graph.TransientShape, 1)
	transient.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		transient.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// ShapeUpdated is the resolver for the shapeUpdated field.
func (r *subscriptionResolver) ShapeUpdated(ctx context.Context, boardID string) (<-chan *graph.Shape, error) {
	ch := make(chan *graph.Shape, 1)
	subscriptions.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		subscriptions.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
